name: Minimal Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  # test:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Setup JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 17
  #     - name: Run Tests
  #       run: bash ./gradlew test --stacktrace  
  build:
    name: Generate And Upload AAR
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build AAR
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload AAR
        uses: actions/upload-artifact@v1
        with:
          name: aar
          path: app/build/outputs/aar/app-debug.aar
  release:
    name: Release AAR
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download AAR from build
        uses: actions/download-artifact@v1
        with:
          name: aar  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} 
      - name: Upload Release AAR
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aar/app-debug.aar
          asset_name: MensaApp.aar
          asset_content_type: application/zip
